server:
  port: 8082

spring:
  elasticsearch:
    uris: http://localhost:9200
  kafka:
    bootstrap-servers: localhost:9092
    listener:
      observation-enabled: true

eureka:
  client:
    enabled: false

logging:
  structured:
    format:
      console: ecs
